// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	M1
	M2
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type M1 struct {
	I                *int32 `protobuf:"varint,1,opt,name=i" json:"i,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *M1) Reset()                    { *m = M1{} }
func (m *M1) String() string            { return proto.CompactTextString(m) }
func (*M1) ProtoMessage()               {}
func (*M1) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *M1) GetI() int32 {
	if m != nil && m.I != nil {
		return *m.I
	}
	return 0
}

type M2 struct {
	I                *uint32 `protobuf:"varint,1,opt,name=i" json:"i,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *M2) Reset()                    { *m = M2{} }
func (m *M2) String() string            { return proto.CompactTextString(m) }
func (*M2) ProtoMessage()               {}
func (*M2) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *M2) GetI() uint32 {
	if m != nil && m.I != nil {
		return *m.I
	}
	return 0
}

func init() {
	proto.RegisterType((*M1)(nil), "main.M1")
	proto.RegisterType((*M2)(nil), "main.M2")
}

var fileDescriptor0 = []byte{
	// 68 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53,
	0xe2, 0xe7, 0x62, 0xf2, 0x35, 0x14, 0xe2, 0xe4, 0x62, 0xcc, 0x94, 0x60, 0x54, 0x60, 0xd4, 0x60,
	0x05, 0x0b, 0x18, 0x21, 0x04, 0x78, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd4, 0xee, 0xa4, 0x66,
	0x37, 0x00, 0x00, 0x00,
}
