// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	IntType1
	IntType2
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type IntType1 struct {
	T1 int32  `protobuf:"varint,1,opt,name=t1" json:"t1,omitempty"`
	T2 int64  `protobuf:"varint,2,opt,name=t2" json:"t2,omitempty"`
	T3 uint32 `protobuf:"varint,3,opt,name=t3" json:"t3,omitempty"`
	T4 uint64 `protobuf:"varint,4,opt,name=t4" json:"t4,omitempty"`
	T5 uint32 `protobuf:"varint,5,opt,name=t5" json:"t5,omitempty"`
	T6 int32  `protobuf:"varint,6,opt,name=t6" json:"t6,omitempty"`
	T7 int64  `protobuf:"varint,7,opt,name=t7" json:"t7,omitempty"`
	T8 int64  `protobuf:"varint,8,opt,name=t8" json:"t8,omitempty"`
	T9 uint32 `protobuf:"varint,9,opt,name=t9" json:"t9,omitempty"`
}

func (m *IntType1) Reset()                    { *m = IntType1{} }
func (m *IntType1) String() string            { return proto.CompactTextString(m) }
func (*IntType1) ProtoMessage()               {}
func (*IntType1) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type IntType2 struct {
	T1 int64 `protobuf:"varint,1,opt,name=t1" json:"t1,omitempty"`
	T2 int64 `protobuf:"varint,2,opt,name=t2" json:"t2,omitempty"`
	T3 int64 `protobuf:"varint,3,opt,name=t3" json:"t3,omitempty"`
	T4 int64 `protobuf:"varint,4,opt,name=t4" json:"t4,omitempty"`
	T5 int64 `protobuf:"varint,5,opt,name=t5" json:"t5,omitempty"`
	T6 int64 `protobuf:"varint,6,opt,name=t6" json:"t6,omitempty"`
	T7 int64 `protobuf:"varint,7,opt,name=t7" json:"t7,omitempty"`
	T8 int64 `protobuf:"varint,8,opt,name=t8" json:"t8,omitempty"`
	T9 int64 `protobuf:"varint,9,opt,name=t9" json:"t9,omitempty"`
}

func (m *IntType2) Reset()                    { *m = IntType2{} }
func (m *IntType2) String() string            { return proto.CompactTextString(m) }
func (*IntType2) ProtoMessage()               {}
func (*IntType2) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*IntType1)(nil), "main.IntType1")
	proto.RegisterType((*IntType2)(nil), "main.IntType2")
}

var fileDescriptor0 = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53,
	0x9a, 0xc5, 0xc8, 0xc5, 0xe1, 0x99, 0x57, 0x12, 0x52, 0x59, 0x90, 0x6a, 0x28, 0xc4, 0xc7, 0xc5,
	0x54, 0x62, 0x28, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x1a, 0x04, 0x64, 0x81, 0xf9, 0x46, 0x12, 0x4c,
	0x40, 0x3e, 0x33, 0x90, 0x6f, 0x04, 0xe6, 0x1b, 0x4b, 0x30, 0x03, 0xf9, 0xbc, 0x40, 0xbe, 0x31,
	0x98, 0x6f, 0x22, 0xc1, 0x02, 0xe4, 0xb3, 0x00, 0xf9, 0x26, 0x60, 0xbe, 0xa9, 0x04, 0x2b, 0x54,
	0xde, 0x14, 0xcc, 0x37, 0x93, 0x60, 0x83, 0x9a, 0x67, 0x06, 0xe6, 0x9b, 0x4b, 0xb0, 0x43, 0xcd,
	0x33, 0x07, 0xf3, 0x2d, 0x24, 0x38, 0xa0, 0x7c, 0x0b, 0x30, 0xdf, 0x52, 0x82, 0x13, 0xaa, 0xdf,
	0x12, 0xd9, 0x71, 0x46, 0x48, 0x8e, 0x63, 0x26, 0xe0, 0x38, 0x66, 0x34, 0xc7, 0x31, 0xa3, 0x39,
	0x8e, 0x19, 0xcd, 0x71, 0xcc, 0x24, 0x3a, 0x0e, 0xc4, 0xb7, 0x4c, 0x62, 0x03, 0x07, 0xa3, 0x31,
	0x20, 0x00, 0x00, 0xff, 0xff, 0x66, 0x7d, 0x7b, 0x7b, 0x57, 0x01, 0x00, 0x00,
}
