// Code generated by protoc-gen-go.
// source: RegMessage.proto
// DO NOT EDIT!

package main

import "fmt"
import proto "github.com/golang/protobuf/proto"
import "github.com/zieckey/gohello/protobuf/protobuf2/req"


func main() {
    regMessage := &req.RegMessage{
        Id:       proto.Int32(10001),
        Username: proto.String("vicky"),
        Password: proto.String("123456"),
        Email:    proto.String("eclipser@163.com"),
    }
    buffer, err := proto.Marshal(regMessage)
    if err != nil {
        fmt.Printf("failed: %s\n", err)
        return
    }

    m := &req.RegMessage{}
    err = proto.Unmarshal(buffer, m)
    fmt.Printf("name=[%v] email=[%v] id=[%v]\n", m.GetUsername(), m.GetEmail(), m.GetId())
/*
    pTCPAddr, err := net.ResolveTCPAddr("tcp", "192.168.1.98:7070")
    if err != nil {
        fmt.Fprintf(os.Stderr, "Error: %s", err.Error())
        return
    }
    pTCPConn, err := net.DialTCP("tcp", nil, pTCPAddr)
    if err != nil {
        fmt.Fprintf(os.Stderr, "Error: %s", err.Error())
        return
    }
    pTCPConn.Write(buffer)
    */
}
