// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	RegMessage
*/
package main

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type RegMessage struct {
	Id       int32             `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Username string            `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Password string            `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	Email    string            `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	Exts     map[string]string `protobuf:"bytes,5,rep,name=exts" json:"exts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *RegMessage) Reset()         { *m = RegMessage{} }
func (m *RegMessage) String() string { return proto.CompactTextString(m) }
func (*RegMessage) ProtoMessage()    {}

func (m *RegMessage) GetExts() map[string]string {
	if m != nil {
		return m.Exts
	}
	return nil
}

func init() {
}
