// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

package main

import proto "github.com/golang/protobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type RegMessage struct {
	Id               *int32                  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Username         *string                 `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Password         *string                 `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	Email            *string                 `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	Exts             []*RegMessage_ExtsEntry `protobuf:"bytes,5,rep,name=exts" json:"exts,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *RegMessage) Reset()         { *m = RegMessage{} }
func (m *RegMessage) String() string { return proto.CompactTextString(m) }
func (*RegMessage) ProtoMessage()    {}

func (m *RegMessage) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *RegMessage) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *RegMessage) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *RegMessage) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

func (m *RegMessage) GetExts() []*RegMessage_ExtsEntry {
	if m != nil {
		return m.Exts
	}
	return nil
}

type RegMessage_ExtsEntry struct {
	Key              *string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value            *string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RegMessage_ExtsEntry) Reset()         { *m = RegMessage_ExtsEntry{} }
func (m *RegMessage_ExtsEntry) String() string { return proto.CompactTextString(m) }
func (*RegMessage_ExtsEntry) ProtoMessage()    {}

func (m *RegMessage_ExtsEntry) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *RegMessage_ExtsEntry) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

func init() {
}
